### ISSUE TITLE
/info -> "The application did not respond"

### ISSUE THREAD

**Issue by femboyfin** [Steam-Ban-Notifier/issues#2]
I was trying to find a way to get the "[PREMIUM ONLY]" `permanent` slash command option for `/add` or at least a link to a support server to ask about it, but `/info` loads for a long time:
![image](https://user-images.githubusercontent.com/18708515/170749803-78fbad03-a8e6-40dc-b042-836826693f0e.png)
then after a long time of waiting you get this
![image](https://user-images.githubusercontent.com/18708515/170750735-e48452e9-6ad8-4744-a22e-54f0f21a794b.png)

**Comment by Invades** [comment]
Bot is broken at the current moment, please be patient for a fix. Also you are not able to pay for premium or anything like that, it was simply a thing added for friends to permanently add accounts to the watchlist(until the account added gets banned once).

**Comment by Invades** [comment]
this has been fixed, still can't join the support server as it's not a thing anymore due to some technicalities.
